var ccb_resources = [
    {type:'image', src:"images/role/run/ccrole.png"},
    {type:'image', src:"images/bg/background.png"},
    {type:'image', src:"images/button/5-1.png"},
    {type:'image', src:"images/frame/btn_1.png"},
    {type:'image', src:"images/button/174-1.png"},
    {type:'image', src:"images/clickme-down.png"},
    {type:'image', src:"images/clickme.png"},
    {type:'image', src:"images/button/174-3.png"},
    {type:'plist', src:"images/role/run/caocao.plist"},
    {type:'image', src:"images/bg/welcom.jpg"},
    {type:'image', src:"images/role/run/streak.png"},
    {type:'ccbi', src:"interface/layout.ccbi"},
    {type:'ccbi', src:"interface/welcom.ccbi"},
    {type:'image', src:"images/role/lc-GS.png"},
    {type:'image', src:"images/button/10-3.png"},
    {type:'image', src:"images/button/174-2.png"},
    {type:'plist', src:"images/role/run/ccrole.plist"},
    {type:'ccbi', src:"interface/linchong.ccbi"},
    {type:'image', src:"images/bg/iso-test.png"},
    {type:'image', src:"images/role/lc-GT.png"},
    {type:'image', src:"images/bg/tile_iso_offset.png"},
    {type:'ccbi', src:"interface/mainScene.ccbi"},
    {type:'image', src:"images/role/lc-GJ.png"},
    {type:'image', src:"images/bg/mygame.jpg"},
];
